### ISSUE TITLE
Precipitation quantile bias

### ISSUE THREAD

**Issue by yifatdzigan** [c3s-magic/c3s-magic-metric-status#10]
This is a tracking issue for the final integration of *Precipitation quantile bias metric* into the MAGIC framework.

This is also a place for discussion and updates on the current status, problems and questions related to this metric.

**Links:**
----------

[Portal](https://portal.c3s-magic.eu/#/diagnostics/quantilebias)
[Recipe](https://github.com/ESMValGroup/ESMValTool/blob/version2_development/esmvaltool/recipes/recipe_quantilebias.yml)
For an overview of the current status of all metrics see [MAGIC Metrics Final Integration Checklist](https://docs.google.com/spreadsheets/d/1LFhEuL6w9KBqFmujVXXN6qj98jigMIPArYkSVKB_Frw/edit#gid=0)

**Contacts:**
--------------
@jhardenberg 
@earnone

**Comment by yifatdzigan** [comment]
@bpmweel Metric tested on DAS 5. Ready for WPS integration. **Note: a new metric in WPS**

**Comment by yifatdzigan** [comment]
@jhardenberg In the readtheodcs the variable used for this recipe is pr daily mean, but the recipe mentiones months. Which one of the two is the correct variable?

**Comment by earnone** [comment]
@yifatdzigan it is monthly data, typo in readthedocs. Can we change it without a pull request?

**Comment by yifatdzigan** [comment]
@earnone I changed and and made a pull request. Thanks :)

**Comment by earnone** [comment]
@yifatdzigan we tested this on 25 cmip5 models or so. Should we be more specific and run it on all available datasets?

**Comment by yifatdzigan** [comment]
@earnone I will discuss this with Bouwe/Niels and let you know.

**Comment by yifatdzigan** [comment]
@earnone I discussed this with Bouwe and he mentioned the requirement is that the metrics work with the entire cp4cds dataset. Testing with 25 models will give reasonable confidence that it works with the entire dataset, but no 100% guarantee. In my opnion (Yifat) this is enough.

**Comment by JaroCamphuijsen** [comment]
@earnone @jhardenberg This metric has now been integrated into WPS and is available on the development portal, can you check whether we have all of the options and settings right?

**Comment by jhardenberg** [comment]
Thanks. It is great that there is an interactive plot.

- It would be nice to have more options for the reference dataset, currently only GPCP-SG can be selected. I would suggest to include also ERA-Interim (tier3) and NCEP (tier2). 
- The label for the start year is "Start year (1850)" and the label for the end year is "End year (till 2005)". 
For the start year it should maybe say "Start year (from 1850)"  (is it checked if a valid selection is made?)
For the end year "till 2005" makes sense only for the historical experiment. For the scenarios (rcp45 etc), it would be "till 2100" ! 
So maybe it would be better to drop the "from 1850" and "till 2005" entirely.
Also, as I remarked somewhere else, what happens if the user selects say [1990 - 2050] for a scenario? The recipe will fail since 1990 is not included in the scenario range. If in the recipe which is created you used a list such as "[historical, rcp45]" instead of "rcp45" for the experiment, this would work correctly instead.

**Comment by earnone** [comment]
This was actually thought to calculate biases vs observations so the period should indeed be restricted to that of observations. 

This implies including concatenation historical+rcp.

In principle of course one may calculate a bias vs a reference model for projections.

**Comment by earnone** [comment]
This is also failing because it cannot reach model data.

**Comment by earnone** [comment]
In the diagnostic webpage on the portal the numbers of the color scale in the interactive plot should be refined, as they currently read (0.0, 1.0, 1.0, 2.0, 2.0), instead of (0.0, 0.5, 1.0, 1.5, 2.0).

The link to the article is wrong. This is the correct one: https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/2013JD021152

**Comment by yifatdzigan** [comment]
I fixed the link to the article

**Comment by earnone** [comment]
The calculation with default settings or with different selection is failing. Is the GPCP-SG  dataset correctly linked? Should we wait for testing?

It is still not possible to change model start and end years. Will this change?

**Comment by jhardenberg** [comment]
GPCP-SG does not work yet, it seems not to find the data.
Actually it would be good to have more than one option for the "Reference dataset" . Currently only  GPCP-SG is possible. Maybe we could also add other datasets which have daily precip, such as Tier2/NCEP, Tier3/Era-Interim and Tier1/TRMM ?

**Comment by rvanharen** [comment]
@jhardenberg I think we decided late last week that we will limit to one reference dataset per metric for the demo due to time constraints. Would GPCP-SG be the best one to use in that case?

**Comment by earnone** [comment]
@rvanharen yes, if only one dataset is included GPCP-SG will be fine.

**Comment by jhardenberg** [comment]
Precipitation quantile bias is missing a "calculate" logo in the Metrics & Diagnostics page https://portal.c3s-magic.eu/#/diagnostics and a "calculate" button in the corresponding landing page (checked on portal.c3s-magic.eu)

**Comment by yifatdzigan** [comment]
> Precipitation quantile bias is missing a "calculate" logo in the Metrics & Diagnostics page https://portal.c3s-magic.eu/#/diagnostics and a "calculate" button in the corresponding landing page (checked on portal.c3s-magic.eu)

We removed  the calculate logo from the landing page for all the metrics

**Comment by earnone** [comment]
@yifatdzigan ok, check [https://github.com/c3s-magic/c3s-magic-frontend/issues/238](https://github.com/c3s-magic/c3s-magic-frontend/issues/238) as one metric in the list still has it.

**Comment by yifatdzigan** [comment]
The updated version will be uploaded in a few hours

**Comment by yifatdzigan** [comment]
> @yifatdzigan ok, check [c3s-magic/c3s-magic-frontend#238](https://github.com/c3s-magic/c3s-magic-frontend/issues/238) as one metric in the list still has it.

The updated version will be uploaded in a few hours
